# molecule.py
import jax.numpy as jnp
import constants as C

def create_water_molecule():
    """
    1つの水分子の初期座標(XYZ)を生成して返す関数
    Returns:
        positions (jnp.array): shape=(3, 3) の配列。単位はÅ。
                               [ [Ox, Oy, Oz],
                                 [H1x, H1y, H1z],
                                 [H2x, H2y, H2z] ]
    """
    # 1. 酸素原子 (原点)
    o_pos = jnp.array([0.0, 0.0, 0.0])
    
    # 2. 水素原子1 (X軸上に配置)
    # 座標: (r, 0, 0)
    h1_pos = jnp.array([C.OH_BOND_LENGTH, 0.0, 0.0])
    
    # 3. 水素原子2 (XY平面上に配置)
    # 角度をラジアンに変換
    theta_rad = jnp.radians(C.HOH_ANGLE)
    
    # 三角関数で座標計算: (r*cos(θ), r*sin(θ), 0)
    h2_x = C.OH_BOND_LENGTH * jnp.cos(theta_rad)
    h2_y = C.OH_BOND_LENGTH * jnp.sin(theta_rad)
    h2_pos = jnp.array([h2_x, h2_y, 0.0])
    
    # 4. 3つの原子を結合して (3,3) の行列にする
    positions = jnp.stack([o_pos, h1_pos, h2_pos])
    
    return positions

def save_xyz(positions, filename="water.xyz"):
    """
    可視化ソフト(VMD, Ovitoなど)で見るためのXYZファイルを出力
    """
    # JAX配列をCPU上の通常のNumPy配列に戻す(ファイル書き込み用)
    import numpy as np
    pos_np = np.array(positions)
    
    with open(filename, 'w') as f:
        f.write("3\n") # 原子の数
        f.write("Water molecule generated by JAX\n") # コメント行
        f.write(f"O  {pos_np[0,0]:.5f} {pos_np[0,1]:.5f} {pos_np[0,2]:.5f}\n")
        f.write(f"H  {pos_np[1,0]:.5f} {pos_np[1,1]:.5f} {pos_np[1,2]:.5f}\n")
        f.write(f"H  {pos_np[2,0]:.5f} {pos_np[2,1]:.5f} {pos_np[2,2]:.5f}\n")
    print(f"Saved: {filename}")

# このファイルを直接実行した時の動作
if __name__ == "__main__":
    pos = create_water_molecule()
    print("Generated Water Molecule Coordinates (Angstrom):")
    print(pos)
    
    save_xyz(pos)
